### ISSUE TITLE
Not checking proper format for email

### ISSUE THREAD

**Issue by tbudhe** [konsumer/mongoose-type-email#12] opened 2018-07-31 21:34 UTC
test6@12
If I just pass this it accepts email. Even though it doesn't have any subdomain like i.e.` .com`, `.co.in` etc.. please let me if you are planning to fix this. But it works perfectly.

**Comment by konsumer** [comment] 2018-11-29 11:16
It's working as expected, and should stay this way, for the default. The address validator follows the format from the [w3c validator](http://www.w3.org/TR/html5/forms.html#valid-e-mail-address). I'd be willing to accept a PR for a config option like `requiresTld` or something.

**Comment by azwar** [comment] 2019-01-18 10:27
I also have the same issue when using this validator.
It pass if I input this text: johndoe@domain, this should not pass.

**Comment by konsumer** [comment] 2019-02-12 00:29
Like I said, it follows the spec (which also allows `johndoe@domain`) but I am willing to accept a PR for another option to make it work the way you want, but I think it should follow the current format, by default.

**Comment by konsumer** [comment] 2019-04-23 21:54
Closing this issue, as it works as intended. Happy to accept a PR for an additional config flag, if you want it to work differently.

**Closed as completed by konsumer** 2019-04-23 21:54 UTC

**Comment by konsumer** [comment] 2020-11-13 03:41
Even though I said I don't want to write the code (but would accept a PR) for an option that enables this unexpected behavior, I ended up just adding it in [this commit](https://github.com/konsumer/mongoose-type-email/commit/07ca26a473124be5b717c3d44c7222f243ac409d). Now you can use `correctTld` in options, and it will validate using validate.js whcih is more extensive than just changing the regex (it checks for valid TLD.)

**Comment by azwar** [comment] 2020-11-13 06:22
Thank you @konsumer
