### ISSUE TITLE
Email Regex 

### ISSUE THREAD

**Issue by pageza** [konsumer/mongoose-type-email#37] opened 2020-11-11 17:26 UTC
While working with this package, I noticed that the email validation regex allows for something like 'email@email' to pass. 
Doing a little searching I found this regex string catches pretty well, may want to consider using it instead.

(?:[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*|"(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21\x23-\x5b\x5d-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])*")@(?:(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?|\[(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?|[a-z0-9-]*[a-z0-9]:(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21-\x5a\x53-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])+)\])

**Comment by konsumer** [comment] 2020-11-13 03:22
This is a dupe of #12 

The regex comes from the [email form-field type spec](https://html.spec.whatwg.org/multipage/input.html#valid-e-mail-address).

This is the intended behavior, but I'd be willing to add an option to make it work differently. I saw your PR (#38 ), which just replaces the regex, but doesn't add an option to switch to the new behavior, and leave the old behavior as default.

While considering this, it might make sense to actually check the TLD, as even if it requires `person@whatever.whatever` it doesn't check if that is a valid TLD. One method of doing this is in [validator.js](https://github.com/validatorjs/validator.js) but this adds a big dictionary of valid TLDs to the library, and requires update when the list changes. I'm open to outsourcing the validation to that lib behind a flag, and then we don't have to worry about it, over here (other than updating the lib from time to time.)

Even though I said earlier I didn't want to implement it (as the current behavior works great for me) maybe something like this:

```js
var isEmail = require('validator/lib/isEmail')

function validateEmail (val, options) {
  var required = (typeof options.required === 'function') ? options.required() : options.required
  var passedAllowBlank = options.allowBlank && (val === '' || val === null)
  if (passedAllowBlank && !required) {
    return true
  }
  return options.correctTld ? isEmail(val) : regEmail.test(val)
}
```

Where you then have a field-option `correctTld` which would ensure it's really a real address, with everything short of sending an email and waiting for a bounce. Does this make sense?

**Comment by konsumer** [comment] 2020-11-13 03:38
Added to mongoose-type-email@1.1.0 We can change the name of the flag, if `correctTld` doesn't make sense.

**Closed as completed** 2020-11-13 03:41 UTC
